using Application.Processes;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Infrastructure.Pdf;

/// <summary>
/// Renders business documents to PDF with QuestPDF. Kept presentational only — totals and risk
/// counts are computed by the caller; this just lays them out.
/// </summary>
public class PdfService : IPdfService
{
    static PdfService() => QuestPDF.Settings.License = LicenseType.Community;

    private static readonly string[] RiskOrder = { "High", "Medium", "Low" };

    public byte[] RenderInvoice(InvoiceDoc doc)
    {
        var total = doc.Items.Sum(i => i.Quantity * i.UnitPrice);

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(t => t.FontSize(10).FontColor(Colors.Grey.Darken3));

                page.Header().Row(row =>
                {
                    row.RelativeItem().Column(col =>
                    {
                        col.Item().Text("INVOICE").FontSize(24).Bold().FontColor(Colors.Blue.Darken2);
                        col.Item().Text($"Issued {DateTime.Now:yyyy-MM-dd}").FontColor(Colors.Grey.Medium);
                    });
                    row.ConstantItem(160).AlignRight().Column(col =>
                    {
                        col.Item().Text("Miriani Assistant").Bold();
                        col.Item().Text("Business Automation").FontColor(Colors.Grey.Medium);
                    });
                });

                page.Content().PaddingVertical(20).Column(col =>
                {
                    col.Item().Text($"Bill to: {doc.Client}").Bold();
                    col.Item().PaddingBottom(10);

                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.RelativeColumn(4);
                            c.RelativeColumn(1);
                            c.RelativeColumn(2);
                            c.RelativeColumn(2);
                        });

                        table.Header(h =>
                        {
                            void Head(string t) => h.Cell().Background(Colors.Grey.Lighten3).Padding(6).Text(t).Bold();
                            Head("Description");
                            Head("Qty");
                            Head("Unit Price");
                            Head("Amount");
                        });

                        foreach (var item in doc.Items)
                        {
                            void Cell(string t) => table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).Padding(6).Text(t);
                            Cell(item.Description);
                            Cell(item.Quantity.ToString("0.##"));
                            Cell($"{item.UnitPrice:0.00} {doc.Currency}");
                            Cell($"{item.Quantity * item.UnitPrice:0.00} {doc.Currency}");
                        }
                    });

                    col.Item().PaddingTop(12).AlignRight().Text($"Total: {total:0.00} {doc.Currency}")
                        .FontSize(14).Bold().FontColor(Colors.Blue.Darken2);

                    if (!string.IsNullOrWhiteSpace(doc.Notes))
                        col.Item().PaddingTop(16).Text(doc.Notes!).Italic().FontColor(Colors.Grey.Medium);
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by Miriani — ").FontColor(Colors.Grey.Medium);
                    t.Span("AI Business Process Automation").FontColor(Colors.Grey.Medium).Italic();
                });
            });
        }).GeneratePdf();
    }

    public byte[] RenderContractReport(ContractReportDoc doc, string title)
    {
        var high = doc.Clauses.Count(c => string.Equals(c.Risk, "High", StringComparison.OrdinalIgnoreCase));

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(t => t.FontSize(10).FontColor(Colors.Grey.Darken3));

                page.Header().Column(col =>
                {
                    col.Item().Text("CONTRACT RISK REVIEW").FontSize(20).Bold().FontColor(Colors.Red.Darken2);
                    col.Item().Text(title).FontColor(Colors.Grey.Medium);
                    col.Item().Text($"Reviewed {DateTime.Now:yyyy-MM-dd}").FontColor(Colors.Grey.Medium);
                });

                page.Content().PaddingVertical(18).Column(col =>
                {
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Text($"Overall risk: {doc.OverallRisk}").FontSize(13).Bold()
                            .FontColor(RiskColor(doc.OverallRisk));
                        row.ConstantItem(180).AlignRight().Text($"{doc.Clauses.Count} clause(s) · {high} high-risk")
                            .FontColor(Colors.Grey.Medium);
                    });

                    col.Item().PaddingTop(12).Table(table =>
                    {
                        table.ColumnsDefinition(c => { c.RelativeColumn(3); c.RelativeColumn(1); c.RelativeColumn(4); });
                        table.Header(h =>
                        {
                            void Head(string t) => h.Cell().Background(Colors.Grey.Lighten3).Padding(6).Text(t).Bold();
                            Head("Clause"); Head("Risk"); Head("Finding");
                        });
                        foreach (var c in doc.Clauses.OrderBy(x => Array.IndexOf(RiskOrder, Title(x.Risk))))
                        {
                            table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).Padding(6).Text(c.Clause);
                            table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).Padding(6)
                                .Text(c.Risk).FontColor(RiskColor(c.Risk)).Bold();
                            table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten2).Padding(6).Text(c.Finding);
                        }
                    });

                    if (doc.Recommendations.Count > 0)
                    {
                        col.Item().PaddingTop(16).Text("Recommendations").Bold();
                        foreach (var r in doc.Recommendations)
                            col.Item().PaddingLeft(8).Text($"•  {r}");
                    }
                });

                page.Footer().AlignCenter().Text("Generated by Miriani — AI Business Process Automation")
                    .FontColor(Colors.Grey.Medium);
            });
        }).GeneratePdf();
    }

    public byte[] RenderTicketReport(TicketReportDoc doc)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Size(PageSizes.A4);
                page.DefaultTextStyle(t => t.FontSize(10).FontColor(Colors.Grey.Darken3));

                page.Header().Column(col =>
                {
                    col.Item().Text("SUPPORT TICKET REPORT").FontSize(20).Bold().FontColor(Colors.Blue.Darken2);
                    col.Item().Text($"{doc.Key} — {doc.Title}").FontColor(Colors.Grey.Medium);
                    col.Item().Text($"Generated {DateTime.Now:yyyy-MM-dd}").FontColor(Colors.Grey.Medium);
                });

                page.Content().PaddingVertical(18).Column(col =>
                {
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Text($"Severity: {doc.Severity}").FontSize(13).Bold()
                            .FontColor(RiskColor(doc.Severity));
                        if (!string.IsNullOrWhiteSpace(doc.Status))
                            row.ConstantItem(180).AlignRight().Text($"Status: {doc.Status}").FontColor(Colors.Grey.Medium);
                    });

                    void Section(string heading, string? body)
                    {
                        if (string.IsNullOrWhiteSpace(body)) return;
                        col.Item().PaddingTop(14).Text(heading).Bold();
                        col.Item().PaddingTop(2).Text(body!);
                    }

                    Section("Summary", doc.Summary);
                    Section("Impact", doc.Impact);
                    Section("Likely root cause", doc.RootCauseHypothesis);

                    if (doc.RecommendedActions.Count > 0)
                    {
                        col.Item().PaddingTop(14).Text("Recommended actions").Bold();
                        foreach (var a in doc.RecommendedActions)
                            col.Item().PaddingLeft(8).Text($"•  {a}");
                    }
                });

                page.Footer().AlignCenter().Text("Generated by Miriani — AI Business Process Automation")
                    .FontColor(Colors.Grey.Medium);
            });
        }).GeneratePdf();
    }

    private static string Title(string s) => string.IsNullOrEmpty(s) ? s : char.ToUpper(s[0]) + s[1..].ToLower();

    private static string RiskColor(string risk) => Title(risk) switch
    {
        "Critical" => Colors.Red.Darken4,
        "High" => Colors.Red.Darken2,
        "Medium" => Colors.Orange.Darken2,
        "Low" => Colors.Green.Darken2,
        _ => Colors.Grey.Darken2,
    };
}
